name = "ShockTube"
uuid = "26b2f303-670f-4a9c-b974-2622b8a2fb46"
authors = ["Alex Ames <aames@wisc.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
